"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.employerVerifyProvider = exports.uanByPanProvider = exports.employmentLatestProvider = exports.employmentByUanProvider = exports.fetchPassbookProvider = exports.listEmployersProvider = exports.validateOtpProvider = exports.generateOtpProvider = exports.fetchUanProvider = void 0;
var uan_fetch_provider_1 = require("./uan.fetch.provider");
Object.defineProperty(exports, "fetchUanProvider", { enumerable: true, get: function () { return uan_fetch_provider_1.fetchUanProvider; } });
var passbook_generate_otp_provider_1 = require("./passbook.generate-otp.provider");
Object.defineProperty(exports, "generateOtpProvider", { enumerable: true, get: function () { return passbook_generate_otp_provider_1.generateOtpProvider; } });
var passbook_validate_otp_provider_1 = require("./passbook.validate-otp.provider");
Object.defineProperty(exports, "validateOtpProvider", { enumerable: true, get: function () { return passbook_validate_otp_provider_1.validateOtpProvider; } });
var passbook_list_employers_provider_1 = require("./passbook.list-employers.provider");
Object.defineProperty(exports, "listEmployersProvider", { enumerable: true, get: function () { return passbook_list_employers_provider_1.listEmployersProvider; } });
var passbook_fetch_provider_1 = require("./passbook.fetch.provider");
Object.defineProperty(exports, "fetchPassbookProvider", { enumerable: true, get: function () { return passbook_fetch_provider_1.fetchPassbookProvider; } });
var employment_fetch_by_uan_provider_1 = require("./employment.fetch-by-uan.provider");
Object.defineProperty(exports, "employmentByUanProvider", { enumerable: true, get: function () { return employment_fetch_by_uan_provider_1.employmentByUanProvider; } });
var employment_fetch_latest_provider_1 = require("./employment.fetch-latest.provider");
Object.defineProperty(exports, "employmentLatestProvider", { enumerable: true, get: function () { return employment_fetch_latest_provider_1.employmentLatestProvider; } });
var uan_fetch_by_pan_provider_1 = require("./uan.fetch-by-pan.provider");
Object.defineProperty(exports, "uanByPanProvider", { enumerable: true, get: function () { return uan_fetch_by_pan_provider_1.uanByPanProvider; } });
var employer_verify_provider_1 = require("./employer.verify.provider");
Object.defineProperty(exports, "employerVerifyProvider", { enumerable: true, get: function () { return employer_verify_provider_1.employerVerifyProvider; } });
